apiVersion: v1
kind: PersistentVolume # Create PV
metadata:
  name: nia-store-volume # Sets PV name
  labels:
    type: local # Sets PV's type
    app: nia-store
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi # Sets PV's size
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/nia-store" # Sets PV's host path
---
apiVersion: v1
kind: PersistentVolumeClaim # Create PVC
metadata:
  name: nia-store-storage-claim # Sets PVC's name
  labels:
    app: nia-store # Defines app to create PVC for
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi # Sets PVC's size
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nia-store-deployment
  labels:
    app: nia-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nia-store
  template:
    metadata:
      labels:
        app: nia-store
    spec:
      containers:
      - name: nia-store
        image: ghcr.io/moxeed/nia-store:v0.0.17
        ports:
        - containerPort: 3000
        volumeMounts:
          - mountPath: /app/storage
            name: nia-store-storage
      volumes:
        - name: nia-store-storage
          persistentVolumeClaim:
            claimName: nia-store-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  name: nia-app-service
spec:
  selector:
    app: nia-store 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nia-store-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: niakalacenter.ir
    http:
      paths:
      - backend:
          service:
            name: nia-app-service
            port:
              number: 80
        path: /
        pathType: Prefix