apiVersion: apps/v1
kind: Deployment
metadata:
  name: nia-store-deployment
  labels:
    app: nia-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nia-store
  template:
    metadata:
      labels:
        app: nia-store
    spec:
      containers:
      - name: nia-store
        image: ghcr.io/moxeed/nia-store:v0.0.6
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nia-app-service
spec:
  selector:
    app: nia-store 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nia-store-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: niakalacenter.ir
    http:
      paths:
      - backend:
          service:
            name: nia-app-service
            port:
              number: 80
        path: /
        pathType: Prefix